// Keeps the PostgreSQL schema + migrations in step with the canonical SQLite schema (prisma/schema.prisma).
//   npm run db:pg:sync -- <migration_name>   regenerate prisma/postgres/schema.prisma and, if the models changed,
//                                            write a new PostgreSQL migration (schema-to-schema diff, offline —
//                                            no database needed)
//   npm run db:pg:check                      exit 1 if the PostgreSQL schema is out of date (CI / tests)
// Cross-platform (Windows/macOS/Linux): only Node built-ins + the local Prisma CLI.
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, rmSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { toPostgres } from "./pg-schema.mjs";

const root = process.cwd();
const canonical = path.join(root, "prisma", "schema.prisma");
const pgDir = path.join(root, "prisma", "postgres");
const pgSchema = path.join(pgDir, "schema.prisma");
const pgMigrations = path.join(pgDir, "migrations");

const prismaBin = path.join(root, "node_modules", "prisma", "build", "index.js");
function prisma(args) {
  return execFileSync(process.execPath, [prismaBin, ...args], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
}

const next = toPostgres(readFileSync(canonical, "utf8"));
const current = existsSync(pgSchema) ? readFileSync(pgSchema, "utf8") : null;
const check = process.argv.includes("--check");

if (check) {
  if (current !== next) {
    console.error("prisma/postgres/schema.prisma is out of date. Run: npm run db:pg:sync -- <migration_name>");
    process.exit(1);
  }
  console.log("PostgreSQL schema is in sync with prisma/schema.prisma.");
  process.exit(0);
}

if (current === next) {
  console.log("PostgreSQL schema already in sync; no migration needed.");
  process.exit(0);
}

mkdirSync(pgMigrations, { recursive: true });
const tmp = path.join(pgDir, ".next-schema.prisma");
writeFileSync(tmp, next);
try {
  const hasMigrations = existsSync(pgMigrations) && readdirSync(pgMigrations).some((d) => /^\d{14}_/.test(d));
  const from = hasMigrations && current ? ["--from-schema", pgSchema] : ["--from-empty"];
  const sql = prisma(["migrate", "diff", ...from, "--to-schema", tmp, "--script"]);
  const name = (process.argv.slice(2).find((a) => !a.startsWith("--")) ?? (hasMigrations ? "update" : "init")).replace(/[^a-z0-9_]/gi, "_");
  const stamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
  const dir = path.join(pgMigrations, `${stamp}_${name}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "migration.sql"), sql);
  writeFileSync(path.join(pgMigrations, "migration_lock.toml"), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n');
  writeFileSync(pgSchema, next);
  console.log(`Wrote ${path.relative(root, pgSchema)} and ${path.relative(root, dir)}/migration.sql`);
} finally {
  rmSync(tmp, { force: true });
}
